#!/bin/sh
VER=`curl -sA - https://www.docker.elastic.co/# | grep "docker pull docker.elastic.co/logstash/logstash-<strong>oss</strong>" | awk '{print $6}' | cut -d':' -f2- | cut -f1 -d"<" | sort -nr | head -n1`
docker tag $DOCKER_REPO $DOCKER_REPO:$VER
docker push $DOCKER_REPO:$VER
