#!/bin/sh
VER=`curl -sA - https://www.docker.elastic.co/r/logstash | tr ' ' '\n' | grep -oE "docker\.elastic\.co/logstash/logstash-oss:[0-9]\.[0-9]\.[0-9]" | cut -d':' -f2- | sort -nr | head -n1`
docker tag $DOCKER_REPO $DOCKER_REPO:$VER
docker push $DOCKER_REPO:$VER
